# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f.xci
# IP: The module: 'imem_f' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_f'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f.xci
# IP: The module: 'imem_f' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_f'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
