# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/MathLogic/modelsim/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Mathlogic/Project/cpu54/cpu.cache/wt [current_project]
set_property parent.project_path D:/Mathlogic/Project/cpu54/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f.xci
set_property is_locked true [get_files d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top imem_f -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all imem_f_

write_checkpoint -force -noxdef imem_f.dcp

catch { report_utilization -file imem_f_utilization_synth.rpt -pb imem_f_utilization_synth.pb }

if { [catch {
  file copy -force D:/Mathlogic/Project/cpu54/cpu.runs/imem_f_synth_1/imem_f.dcp d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Mathlogic/Project/cpu54/cpu.ip_user_files/ip/imem_f]} {
  catch { 
    file copy -force d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_stub.v D:/Mathlogic/Project/cpu54/cpu.ip_user_files/ip/imem_f
  }
}

if {[file isdir D:/Mathlogic/Project/cpu54/cpu.ip_user_files/ip/imem_f]} {
  catch { 
    file copy -force d:/Mathlogic/Project/cpu54/cpu.srcs/sources_1/ip/imem_f/imem_f_stub.vhdl D:/Mathlogic/Project/cpu54/cpu.ip_user_files/ip/imem_f
  }
}
